version: '3'
services:
  mmr:
    build: .
    image: catclaws/mmr-assembly
    volumes:
      - ../:/docker
    working_dir: /docker/assembly
    command: bash -c 'export PATH="$$PATH:/opt/n64/bin" && make copy'
