version: '3'
services:
  mmr:
    build: .
    volumes:
      - ../:/docker
    working_dir: /docker/assembly
    #stdin_open: true
    #tty: true
    command: bash -c 'export PATH="$$PATH:/opt/n64/bin" && make'